/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ambibright_engine_jni_DirectXCapture */

#ifndef _Included_ambibright_engine_jni_DirectXCapture
#define _Included_ambibright_engine_jni_DirectXCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ambibright_engine_jni_DirectXCapture
 * Method:    initDirectX
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ambibright_engine_jni_DirectXCapture_initDirectX
  (JNIEnv *, jclass, jint);

/*
 * Class:     ambibright_engine_jni_DirectXCapture
 * Method:    captureScreenDirectX
 * Signature: (IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ambibright_engine_jni_DirectXCapture_captureScreenDirectX
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     ambibright_engine_jni_DirectXCapture
 * Method:    destroyDirectX
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ambibright_engine_jni_DirectXCapture_destroyDirectX
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
