/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ambibright_engine_jni_GdiCapture */

#ifndef _Included_ambibright_engine_jni_GdiCapture
#define _Included_ambibright_engine_jni_GdiCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ambibright_engine_jni_GdiCapture
 * Method:    captureScreen
 * Signature: (IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ambibright_engine_jni_GdiCapture_captureScreen
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     ambibright_engine_jni_GdiCapture
 * Method:    captureScreenBuffer
 * Signature: (IIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ambibright_engine_jni_GdiCapture_captureScreenBuffer
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     ambibright_engine_jni_GdiCapture
 * Method:    freeBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_ambibright_engine_jni_GdiCapture_freeBuffer
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
