/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ambibright_engine_jni_GdiCapture */

#ifndef _Included_ambibright_engine_jni_GdiCapture
#define _Included_ambibright_engine_jni_GdiCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ambibright_engine_jni_GdiCapture
 * Method:    captureScreen
 * Signature: (IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ambibright_engine_jni_GdiCapture_captureScreen
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
